### PR TITLE
Update menu.lua

### PR DESCRIPTION
**Pull request by tastymeowmix**
these changes add every button into the practice tool along with old teleport locations.

### CODE REVIEW

**Comment by oberien** [comment]
Thanks for this Pull Request, I like it. I tested it on 1920x1080 and all options are visible. Do you know if all practice options are also visible if playing on 1280x720, or are some of them off-screen?

**Comment by tastymeowmix** [comment]
hey sorry for taking ages to get back to you. some of them are off screen. you can put the font size to 1 to get them all on though. however a scroll option would be nice but i dont entirely know how to add it. also i tried @ing you on discord and got nothing so i guess ill ask here. is it possible to add a function that lets you see whether you are grounded or not.

**Comment by oberien** [comment]
Re discord: I'm locked out of my account and will never get back access.  So for now (probably for another few months) I won't have a discord account.

Implementing scrolling might be pretty hard. If some options are off-screen on 720p, I'd suggest putting the practice points at the beginning such that some buttons are off-screen. I assume that most people would like to train the specific practice points. Also if buttons are off-screen, one can count them to find the correct button.

**Comment by tastymeowmix** [comment]
alright thats shitty you got locked out of your account. ill make it so that the buttons come after the trick practice part.

**Comment by oberien** [comment]
Thanks for the PR, I like the changes.

**Comment by oberien** [comment]
I made a new release for everyone to download: https://github.com/oberien/refunct-tas/releases/tag/v0.6.2

**Pull request merged**
